---
- hosts: webservers
  remote_user: root
  become: true
  tasks:
  - name: Remove residual packages
    apt:
       autoremove: yes
  - name: Install Nginx Package
    package:
      name: nginx
      state: latest
  - name: Ensure Nginx is running
    service:
      name: nginx
      state: started
